use std::collections::HashMap;
use std::iter::Iterator;
use std::path::{PathBuf};
use std::process::Output;
use bio::io::fasta;
use anyhow::{Result, Context, anyhow};
use bio::alignment::Alignment;
use nalgebra::DMatrix;
use colored::Colorize;
use bio::alignment::pairwise::*;
use bio::scores::blosum62;
use crate::{tools, utils};
use bio::pattern_matching::ukkonen::{Ukkonen, unit_cost};
use bio::pattern_matching::horspool::Horspool;
use bio::pattern_matching::myers::Myers;
use serde_json::to_vec;
use utils::translate;

const VERSION: &str = "0.1.0";

fn find_best_alignment(pattern: &[u8], query: &[u8], max_distance: u8) -> Result<Alignment>{

    let mut pattern= Myers::<u64>::new(pattern);
    let mut matches = pattern.find_all_lazy(query, max_distance);

    // TODO: What happens if we have multiple acceptable matches?
    let (best_match_end_idx, dist) =  matches.by_ref().min_by_key(|&(_, dist)| dist).unwrap();

    log::info!("Best match found ending at {} with distance {}", best_match_end_idx, dist);

    let mut alignment = Alignment::default();
    matches.alignment_at(best_match_end_idx, &mut alignment);

    Ok(alignment)
}

fn process_sequence(consensus_start_kmer: &[u8],
                    consensus_end_kmer: &[u8],
                    query: &[u8],
                    max_align_distance: u8,
                    output_type: &String) -> Result<Vec<u8>>{

    // Note - the end kmer is assumed to be reversed already!
    let query_reversed = query.iter().rev().cloned().collect::<Vec<u8>>();
    let start_aln = find_best_alignment(consensus_start_kmer, query, 2)?;
    let end_aln = find_best_alignment(consensus_end_kmer, query_reversed.as_slice(), 2)?;


    log::info!("Found an alignment for the start k-mer from {} to {} (dist {}) and alignment for the send k-mer from {} to {} (dist {})",
        start_aln.ystart, start_aln.yend, start_aln.score,
        end_aln.ystart, end_aln.yend, end_aln.score
    );

    let start_trim = start_aln.ystart;
    let end_trim = query.len() - end_aln.ystart+1;
    let trimmed_query = &query[start_trim..end_trim].to_owned();

    if output_type == "AA" {
        let translated_query = translate::translate(trimmed_query, false, false)?;
        Ok(translated_query)
    }else{
        if output_type != "NT"{
            log::warn!("Output type not recognized, outputting NT sequence.")
        }

        Ok(trimmed_query.to_vec())
    }
}

pub fn run()-> Result<()>{
    simple_logger::SimpleLogger::new().env().init()?;
    let consensus = b"ATGAGAGTGAGGGGGACACTGAGGAATTATCTACCTTGGTGGATATGGGGAATCTTAGGCTTTTGGATAATGAGTTATAATGTGGGGGGAAACTTGTGGGTCACAGTCTATTATGGGGTACCTGTGTGGAGAGAAGCAAAAACTACTCTGTTCTGTGCATCAGATGCTAAAGCATATGACAAAGAAGTGCACAATGTCTGGGCTACACATGCCTGTGTACCCACAGACCCCAACCCACAAAAAATGGTTTTGGGAAATGTAACAGAAAATTTTAACATGTGGAAAAATGACATGGTGGATCAGATGCATGAGGATATAATCAGTTTATGGGATCAAAGTCTAAAGCCATGTGTAAAGTTGACCCCACTCTGTGTCACTTTAAATTGTACTGAGGTAGCTAAGGCTACTGGCAATTTCACGGGAGTAGAAATGAAAAATTGCTCTTTCAATACAACCACAGAATTAAGAGACAGGACACGGAAAGCATATGCACTCTTTTATAGACAGGATATAGTACCACTTGAAGAGAATAAGAATAGCTCTGAGTATATATTAATAAATTGCAATACCTCAACCATAACACAAGCCTGTCCAAAGGTCACCTTTGACCCAATTCCTATACATTATTGTGCTCCAGCTGGTTATGCGATTCTAAAATGTAATAATCAGACATTCAATGGGACAGGACCATGCCTTAATGTTAGTACAGTACAATGTACACATGGGATTAAGCCAGTGGTATCAACTCAACTACTGTTAAATGGTAGCATAGCAGGAAAAGAGATAGTAATTAGATCTGCAAATCTGTCAGACAATGCCAAAACAATAATAGTACATCTTAATGAATCTGTAGAAATTCAGTGTATAAGACCTAACAATAATACAAGGAAAAGTATAAGGATAGGGCCAGGACAAACATTCTATGCAAATAATGACATAATAGGAGACATAAGACAAGCACATTGTAACATTAGTAAAACAAAATGGAATGGAACTTTAGAAAGGGTAAAGGAGAAATTAAAAGTACACTTCCCTAATAAAACAATACAATTTAAACCATCCTCAGGAGGGGACCTAGAAATTACAACACATAGCTTTAATTGTAGAGGAGAATTTTTTTATTGCAATACATCAGGCTTATTTAATAGTAATAGTACATACTTAAATTCAACAAAAAATAATTCAACAGACATCACAATTACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGGGGTAGGACGAGCAATGTATGCCCCTCCCATTGAAGGAAACATAACATGTACCTCAAGTATCACAGGACTACTATTGACACGGGATGGAGGTAAGAACAACACAGAAAATAATACAGAGATATTCAGGCCTGGAGGAGGAAATATGAAGGACAATTGGAGAAGTGAATTATATAAATATAAAGTGGTAGAAATTAAACCATTAGGAATAGCACCCACTAAAGCAAAAAGGAGAGTGGTGGAGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTGTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCGGCGTCAATAACGCTGACGGTACAGGCCAGACAACTGTTGTCTGGTATAGTGCAACAGCAAAGCAATTTGCTGAGAGCTATAGAGGCGCAACAGCATATGTTGCAACTCACGGTCTGGGGCATTAAGCAGCTCCAAGCAAGAGTCCTGGCTATAGAAAGATACCTAAAGGATCAACAGCTCCTAGGAATTTGGGGCTGCTCTGGAAAACTCATCTGCACCACTGCTGTACCTTGGAACTCCAGTTGGAGTAATAAATCTCTAGATGATATTTGGGAAAACATGACCTGGATGCAGTGGGACAAAGAAATTAGTAATTACTCAAACACAATATACAAGTTGCTTGAAGCATCGCAAACCCAGCAGGAGCAAAATGAAAAGGATTTATTAGCATTGGACAAGTGGCAAAATCTGTGGAGTTGGTTTAGCATAACAAATTGGCTATGGTATATAAAAATATTCATAATGATAGTAGGAGGCTTGATAGGTTTAAGAATAATTTTTGCTGTGCTATCTATAGTAAATAGAGTTAGGCAGGGATACTCACCTTTGTCGTTTCAGACCCTTATCCCAGACCCGAGGGGACCCGACAGGCCCGGAGGAATCGAAGAAGAAGGTGGAGAGCAAGACAGAAACAGATCAGTGAGATTAGTGAACGGATTCTTAGCACTTGTCTGGGACGATCTGCGGAGCCTGTGCCTCTTCAGCTACCACCGATTGAGAGACTGCATATTGGGACTGAAACTTCTGGGACAGAGGGGATGGGAAGCCCTTAAGTATCTAGGAAGTCTTGTGCAGTATTGGGGTCTGGAACTAAAAAAGAGTGCCATTAGTCTGCTTGATACCATAGCAATAGTAGTAGCTGAGGGAACAGATAGAATTATAGAATTCATACTAAGAATTTGTAGAGCTATCCACCACATACCTAGAAGAGTAAGACAGGGCTTTGAAGCAGCTTTGCTATAA";
    let query = b"ATGGCAGGAAGAAGCGGAGACAGCGACGACGCACTCCTCCTCGCAGTGAGGATCATCAAAATCCTATATCAAAGCAGTAAGTATATGTAATGTTAGATTTAAGTGCAAGAATAGATTATAGATTAGGAGTAGGAGCACTGATAATAGCATTAATCATAGCAATAGTTGTGTGGATCATAGTATATATAGAATATAGGAAACTATTAAGACAAAGAAAAATAGACTGGTTAATTAAAAGAATTAGGGAGAGAGCAGAAGACAGTGGCAATGAGAGTGAAGGGGATACAGAGGAATTGGCCACAATGGTGGATATGGGGCATCTTAGGCTTTTGGATGATAATAATTTGTAGGGGAACGGGAAACTTGTGGGTCACAGTCTACTATGGGGTACCTGTGTGGAGAGAAGCAAAAACTACTCTATTTTGTGCATCAGATGCTAAAGCATATGAGAGAGAAGTGCATAATGTCTGGGCTACACATGCCTGTGTACCCACAGACCCCAACCCACAAGAACTAGTTTTGGAAAATGTAACAGAAAATTTTAACATGTGGAAAAATGACATGGTAGATCAGATGCATGAAGATATAATCAGTTTATGGGATCAAAGCCTCAAACCATGTGTAAAGTTGACCCCGCTCTGTGTCACTTTAAACTGTAGCAATGCAAATGTTACAAATAGCAATGTCACCGCAAAGGTCAACGCAAGTGAAGAAATGAAAAATTGCTCTTTCAATATAACCACAGAAATAAGAGATAAGGAAAAGAAAGAAAATGCACTATTTTATAAACTTGATATAGTACCACTTGATAGTAACAATTCTAGTATGTATAGATTAATAAACTGTAATACCTCAGTCATGACACAAGCCTGTCCAAAGGTCACTTTTGACCCAATTCCTATACATTATTGTGCTCCAGCTGGGTATGCGATTCTAAAGTGTAATAATAAGACTTTCAATGGCACAGGACCATGCAATAATGTCAGCACAGTACAATGTACACATGGAATTAGGCCAGTGGTTTCAACTCAACTGTTGCTAAATGGTAGCCTAGCAGAAGAAGAGATAATAATTAGATCTGAGAATCTGACAAACAATGTCAAAACAATAATAGTACATCTCAATGAATCTGTAGAGATTAATTGTACAAGACCCAGTAATAATACAAGAAAAAGTATAAGAATAGGACCAGGACAAACATTCTATGCAACAGGAGAAATAATAGGAGATATAAGGCAAGCACATTGTAACATTAGTAAAGCAAGATGGAATACAACTTTACAAAGAGTAAAGATAAAATTAGGGGAACACTTCCCTAGTAGGAATATAACATTTAAATCACCCTCAGGAGGGGACCTGGAAATTACAACACATAGCTTTAACTGTAGAGGAGAATTTTTCTATTGCAATACATCAAACCTGTTTAATGAGACAGACCTAAACATAAATAGCACCACCATCACACTCCAATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTGGGACGAGCAATGTATGCCCCTCCCATTGCAGGAAACATAATATGTAGATCTAATATCACAGGACTACTGTTGACACGAGATGGAGGAAATACAACATCAAATGAGATATTCAGACCTGGAGGAGGAGATATGAGAGATAATTGGAGAAATGAATTATATAAATATAAAGTGGTAGAAATTAAGCCATTAGGAATAGCACCCACTGAGGCAAAAAGGAGAGTGGTGCAGAGAGAGAAAAGAGCAGTGGGAATAGGAGCTGTGTTCCTTGGGTTCTTGGGAGTGGCAGGAAGCACTATGGGCGCGGCGTCAATAACGCTGACGGTACAGGCCAGACAACTGTTGTCTGGTATAGTGCAACAGCAAAACAATTTGCTGAGAGCTATAGAGGCGCAACAGCATATGTTGCAACTCACAGTCTGGGGCATCAAGCAGCTCCAGGCAAGAGTCCTGGCCATAGAAAGATACCTACAGGATCAACAGCTCCTGGGGATATGGGGCTGCTCTGGAAAACTCATTTGCACCACTAATGTGCCTTGGAACTCTAGTTGGAGTAATAAAACTCTAGGTGATATTTGGGATAACATGACCTGGATGCAGTGGGACAGAGAAATTAGTAACTATACAAACACAATATACAGTTTGCTTGAAGAATCGCAAATCCAGCAGGAGAAAAATGAAAAAGATTTATTAGCATTGGACAGGTGGAACAATCTGTGGAATTGGTTTAACATAACAAAATGGCTGTGGTATATAAAGATATTCATAATGATAGTAGGAGGCTTAATAGGTTTAAGAATAATTTTTGCTGTGCTCTCTCTAGTGAATAGAGTTAGGCAGGGATACTCACCTTTATCGTTTCAGACCCTTATCCCAAACCCGAGGGGACCCGACAGGCTCGGAAGAATCGAAGAAGAAGGTGGAGAGCAAGACAGAAACAGATCCGTGCGATTAGTGAGCGGATTCTTACCACTCATCTGGGACGACCTACGGAGCCTGTGCCTCTTCAGCTACCACCAATTGAGAGACTTCATATTGATTGTAGCGAGAGCAGTGGAACTTCTGGGACGCAGCAGTCTCAGGGGACTACAGAGGGGGTGGGAAATCCTTAAATATCTGGGAAATCTTCTGCAATATTGGGGTCTAGAGCTAAAAAAGAGTGCCACTAGTCTGCTTGATAGTTTAGCAATAACAGTAGCTGAAGGAACAGATAGGATTATAGAATTCATACAAAGATTCTGTAGAGCTATCTACAACATACCTAGAAGAATAAGACAGGGTTTTGAAGCAGCTTTGCAATAGAATGGGGAACAAATGGTCAAAAAGCTGGCCTGCTGTGAGAGAAAGAATAAGACGAACTGAGCCAGCAGCAGAGGGAGTAGGAGCAGCATCTCAGGACTTAGATAAACATGGAGCGCTTACAACCAGCAACACAGCCCACAATAATGCTGATTGTGCCTGGCTGCAAGCACAAGAGGAGGAGGAAGAAGTA";

    let final_index = consensus.len() - 10;
    let start_query = &consensus[0..10];
    let end_query= consensus[final_index..].iter().rev().cloned().collect::<Vec<u8>>();

    let trimmed_seq = process_sequence(start_query, end_query.as_slice(), query, 2, &String::from("AA"))?;
    log::info!("Success: {:?}", String::from_utf8(trimmed_seq)?);


    Ok(())
}