use std::collections::HashMap;
use std::iter::Iterator;
use std::path::{PathBuf};
use bio::io::fasta;
use anyhow::{Result, Context, anyhow};
use nalgebra::DMatrix;
use colored::Colorize;
use bio::alignment::pairwise::*;
use bio::alignment::AlignmentOperation::*;
use bio::scores::blosum62;

const VERSION: &str = "0.1.0";


const GAP_CHAR: u8 = b"-"[0];
const FRAMESHIFT_CHAR: u8 = b"X"[0];
 const UNKNOWN_AA_CHAR: u8 = b"?"[0];

fn translate(dna_seq: &[u8], strip_gaps: bool, ignore_gap_codons: bool, codon_table: &HashMap<&[u8; 3], &[u8; 1]>) -> Result<Vec<u8>>{
    let mut new_seq = dna_seq.to_vec();
    if strip_gaps{
        new_seq = new_seq.iter().copied().filter(|character| *character != GAP_CHAR).collect();
    }
    println!("{:?}",new_seq.len());
    let mut amino_acids = Vec::with_capacity(new_seq.len()/3);
    for codon in new_seq.chunks(3) {

        // If the codon is not a multiple of 3, we will always want to replace it with an incomplete amino acid, so we don't need to
        // check anything else.

        if codon.len() != 3 {
            log::warn!("The codon {:?} had a length of {} so we're adding a {}", String::from_utf8(codon.to_vec()), codon.len(), UNKNOWN_AA_CHAR);
            amino_acids.push(FRAMESHIFT_CHAR);
        } else {
            let nt_triplet: [u8; 3] = codon.try_into().expect("The codon should always be a triplet vector since we've checked for it.");
            let amino_acid = codon_table
                .get(&nt_triplet)
                .with_context(|| format!("Couldn't find amino acid {:?}", String::from_utf8(nt_triplet.to_vec())))
                .unwrap_or(&&[UNKNOWN_AA_CHAR,]);

            amino_acids.push(amino_acid.clone()[0]);
        }
    }


    // let amino_acids: Vec<u8> = new_seq
    //     .chunks(3)
    //     .map(|codon| codon_table.get::<[u8; 3]>(codon.try_into().unwrap()).unwrap()[0])
    //     .collect();
    //
    // println!("{:?}", String::from_utf8(amino_acids.to_vec()))

    Ok(amino_acids)
}

pub fn run() -> Result<()>{
    let codon_table: HashMap<&[u8; 3], &[u8; 1]> = HashMap::from([
        (b"TTT", b"F"),
        (b"TTC", b"F"),
        (b"TTA", b"L"),
        (b"TTG", b"L"),
        (b"CTT", b"L"),
        (b"CTC", b"L"),
        (b"CTA", b"L"),
        (b"CTG", b"L"),
        (b"ATT", b"I"),
        (b"ATC", b"I"),
        (b"ATA", b"I"),
        (b"ATG", b"M"),
        (b"GTT", b"V"),
        (b"GTC", b"V"),
        (b"GTA", b"V"),
        (b"GTG", b"V"),
        (b"TCT", b"S"),
        (b"TCC", b"S"),
        (b"TCA", b"S"),
        (b"TCG", b"S"),
        (b"CCT", b"P"),
        (b"CCC", b"P"),
        (b"CCA", b"P"),
        (b"CCG", b"P"),
        (b"ACT", b"T"),
        (b"ACC", b"T"),
        (b"ACA", b"T"),
        (b"ACG", b"T"),
        (b"GCT", b"A"),
        (b"GCC", b"A"),
        (b"GCA", b"A"),
        (b"GCG", b"A"),
        (b"TAT", b"Y"),
        (b"TAC", b"Y"),
        (b"CAT", b"H"),
        (b"CAC", b"H"),
        (b"CAA", b"Q"),
        (b"CAG", b"Q"),
        (b"AAT", b"N"),
        (b"AAC", b"N"),
        (b"AAA", b"K"),
        (b"AAG", b"K"),
        (b"GAT", b"D"),
        (b"GAC", b"D"),
        (b"GAA", b"E"),
        (b"GAG", b"E"),
        (b"TGT", b"C"),
        (b"TGC", b"C"),
        (b"TGG", b"W"),
        (b"CGT", b"R"),
        (b"CGC", b"R"),
        (b"CGA", b"R"),
        (b"CGG", b"R"),
        (b"AGT", b"S"),
        (b"AGC", b"S"),
        (b"AGA", b"R"),
        (b"AGG", b"R"),
        (b"GGT", b"G"),
        (b"GGC", b"G"),
        (b"GGA", b"G"),
        (b"GGG", b"G"),
        (b"TAA", b"*"),
        (b"TAG", b"*"),
        (b"TGA", b"*")]);
    let reference = b"ATGAGAGTGAAGGAGAAATATCAGCACTTGTGGAGATGGGGGTGGAGATGGGGCACCATGCTCCTTGGGATGTTGATGATCTGTAGTGCTACAGAAAAATTGTGGGTCACAGTCTATTATGGGGTACCTGTGTGGAAGGAAGCAACCACCACTCTATTTTGTGCATCAGATGCTAAAGCATATGATACAGAGGTACATAATGTTTGGGCCACACATGCCTGTGTACCCACAGACCCCAACCCACAAGAAGTAGTATTGGTAAATGTGACAGAAAATTTTAACATGTGGAAAAATGACATGGTAGAACAGATGCATGAGGATATAATCAGTTTATGGGATCAAAGCCTAAAGCCATGTGTAAAATTAACCCCACTCTGTGTTAGTTTAAAGTGCACTGATTTGAAGAATGATACTAATACCAATAGTAGTAGCGGGAGAATGATAATGGAGAAAGGAGAGATAAAAAACTGCTCTTTCAATATCAGCACAAGCATAAGAGGTAAGGTGCAGAAAGAATATGCATTTTTTTATAAACTTGATATAATACCAATAGATAATGATACTACCAGCTATAAGTTGACAAGTTGTAACACCTCAGTCATTACACAGGCCTGTCCAAAGGTATCCTTTGAGCCAATTCCCATACATTATTGTGCCCCGGCTGGTTTTGCGATTCTAAAATGTAATAATAAGACGTTCAATGGAACAGGACCATGTACAAATGTCAGCACAGTACAATGTACACATGGAATTAGGCCAGTAGTATCAACTCAACTGCTGTTAAATGGCAGTCTAGCAGAAGAAGAGGTAGTAATTAGATCTGTCAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAACACATCTGTAGAAATTAATTGTACAAGACCCAACAACAATACAAGAAAAAGAATCCGTATCCAGAGAGGACCAGGGAGAGCATTTGTTACAATAGGAAAAATAGGAAATATGAGACAAGCACATTGTAACATTAGTAGAGCAAAATGGAATAACACTTTAAAACAGATAGCTAGCAAATTAAGAGAACAATTTGGAAATAATAAAACAATAATCTTTAAGCAATCCTCAGGAGGGGACCCAGAAATTGTAACGCACAGTTTTAATTGTGGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGTTTAATAGTACTTGGAGTACTGAAGGGTCAAATAACACTGAAGGAAGTGACACAATCACCCTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGAAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGTGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAATAGCAACAATGAGTCCGAGATCTTCAGACCTGGAGGAGGAGATATGAGGGACAATTGGAGAAGTGAATTATATAAATATAAAGTAGTAAAAATTGAACCATTAGGAGTAGCACCCACCAAGGCAAAGAGAAGAGTGGTGCAGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTTTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCAGCCTCAATGACGCTGACGGTACAGGCCAGACAATTATTGTCTGGTATAGTGCAGCAGCAGAACAATTTGCTGAGGGCTATTGAGGCGCAACAGCATCTGTTGCAACTCACAGTCTGGGGCATCAAGCAGCTCCAGGCAAGAATCCTGGCTGTGGAAAGATACCTAAAGGATCAACAGCTCCTGGGGATTTGGGGTTGCTCTGGAAAACTCATTTGCACCACTGCTGTGCCTTGGAATGCTAGTTGGAGTAATAAATCTCTGGAACAGATTTGGAATCACACGACCTGGATGGAGTGGGACAGAGAAATTAACAATTACACAAGCTTAATACACTCCTTAATTGAAGAATCGCAAAACCAGCAAGAAAAGAATGAACAAGAATTATTGGAATTAGATAAATGGGCAAGTTTGTGGAATTGGTTTAACATAACAAATTGGCTGTGGTATATAAAATTATTCATAATGATAGTAGGAGGCTTGGTAGGTTTAAGAATAGTTTTTGCTGTACTTTCTATAGTGAATAGAGTTAGGCAGGGATATTCACCATTATCGTTTCAGACCCACCTCCCAACCCCGAGGGGACCCGACAGGCCCGAAGGAATAGAAGAAGAAGGTGGAGAGAGAGACAGAGACAGATCCATTCGATTAGTGAACGGATCCTTGGCACTTATCTGGGACGATCTGCGGAGCCTGTGCCTCTTCAGCTACCACCGCTTGAGAGACTTACTCTTGATTGTAACGAGGATTGTGGAACTTCTGGGACGCAGGGGGTGGGAAGCCCTCAAATATTGGTGGAATCTCCTACAGTATTGGAGTCAGGAACTAAAGAATAGTGCTGTTAGCTTGCTCAATGCCACAGCCATAGCAGTAGCTGAGGGGACAGATAGGGTTATAGAAGTAGTACAAGGAGCTTGTAGAGCTATTCGCCACATACCTAGAAGAATAAGACAGGGCTTGGAAAGGATTTTGCTATAA";
    let consensus= b"ATGGCAGGAAGAAGCGGAGACAGCGACGACGCGCTCCTCCTAGCAGTGAGACTCATCAAAATCCTGCATCAAAGCAGTAAGTATATGTAATGCTGAACTTATTAGCAAGAGTAGATTATAGAATAGGAATAGGAGCATTTACAGTAGCATTAATCATAGCAATAGTTGTGTGGATCATAGTATATATAGAATATAGAAAATTGGTAAGACAAAGGAGAATAGATAGGTTAATTAAAAGAATTAGGGAAAGAGCAGAAGACAGTGGCAATGAGAGTGAGGGGGACACTGAGGAATTATCTACCTTGGTGGATATGGGGAATCTTAGGCTTTTGGATAATGAGTTATAATGTGGGGGGAAACTTGTGGGTCACAGTCTATTATGGGGTACCTGTGTGGAGAGAAGCAAAAACTACTCTGTTCTGTGCATCAGATGCTAAAGCATATGACAAAGAAGTGCACAATGTCTGGGCTACACATGCCTGTGTACCCACAGACCCCAACCCACAAAAAATGGTTTTGGGAAATGTAACAGAAAATTTTAACATGTGGAAAAATGACATGGTGGATCAGATGCATGAGGATATAATCAGTTTATGGGATCAAAGTCTAAAGCCATGTGTAAAGTTGACCCCACTCTGTGTCACTTTAAATTGTACTGAGGTAGCTAAGGCTACTGGCAATTTCACGGGAGTAGAAATGAAAAATTGCTCTTTCAATACAACCACAGAATTAAGAGACAGGACACGGAAAGCATATGCACTCTTTTATAGACAGGATATAGTACCACTTGAAGAGAATAAGAATAGCTCTGAGTATATATTAATAAATTGCAATACCTCAACCATAACACAAGCCTGTCCAAAGGTCACCTTTGACCCAATTCCTATACATTATTGTGCTCCAGCTGGTTATGCGATTCTAAAATGTAATAATCAGACATTCAATGGGACAGGACCATGCCTTAATGTTAGTACAGTACAATGTACACATGGGATTAAGCCAGTGGTATCAACTCAACTACTGTTAAATGGTAGCATAGCAGGAAAAGAGATAGTAATTAGATCTGCAAATCTGTCAGACAATGCCAAAACAATAATAGTACATCTTAATGAATCTGTAGAAATTCAGTGTATAAGACCTAACAATAATACAAGGAAAAGTATAAGGATAGGGCCAGGACAAACATTCTATGCAAATAATGACATAATAGGAGACATAAGACAAGCACATTGTAACATTAGTAAAACAAAATGGAATGGAACTTTAGAAAGGGTAAAGGAGAAATTAAAAGTACACTTCCCTAATAAAACAATACAATTTAAACCATCCTCAGGAGGGGACCTAGAAATTACAACACATAGCTTTAATTGTAGAGGAGAATTTTTTTATTGCAATACATCAGGCTTATTTAATAGTAATAGTACATACTTAAATTCAACAAAAAATAATTCAACAGACATCACAATTACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGGGGTAGGACGAGCAATGTATGCCCCTCCCATTGAAGGAAACATAACATGTACCTCAAGTATCACAGGACTACTATTGACACGGGATGGAGGTAAGAACAACACAGAAAATAATACAGAGATATTCAGGCCTGGAGGAGGAAATATGAAGGACAATTGGAGAAGTGAATTATATAAATATAAAGTGGTAGAAATTAAACCATTAGGAATAGCACCCACTAAAGCAAAAAGGAGAGTGGTGGAGAGAGAAAAAAGAGCAGTGGGAATAGGAGCTGTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCGGCGTCAATAACGCTGACGGTACAGGCCAGACAACTGTTGTCTGGTATAGTGCAACAGCAAAGCAATTTGCTGAGAGCTATAGAGGCGCAACAGCATATGTTGCAACTCACGGTCTGGGGCATTAAGCAGCTCCAAGCAAGAGTCCTGGCTATAGAAAGATACCTAAAGGATCAACAGCTCCTAGGAATTTGGGGCTGCTCTGGAAAACTCATCTGCACCACTGCTGTACCTTGGAACTCCAGTTGGAGTAATAAATCTCTAGATGATATTTGGGAAAACATGACCTGGATGCAGTGGGACAAAGAAATTAGTAATTACTCAAACACAATATACAAGTTGCTTGAAGCATCGCAAACCCAGCAGGAGCAAAATGAAAAGGATTTATTAGCATTGGACAAGTGGCAAAATCTGTGGAGTTGGTTTAGCATAACAAATTGGCTATGGTATATAAAAATATTCATAATGATAGTAGGAGGCTTGATAGGTTTAAGAATAATTTTTGCTGTGCTATCTATAGTAAATAGAGTTAGGCAGGGATACTCACCTTTGTCGTTTCAGACCCTTATCCCAGACCCGAGGGGACCCGACAGGCCCGGAGGAATCGAAGAAGAAGGTGGAGAGCAAGACAGAAACAGATCAGTGAGATTAGTGAACGGATTCTTAGCACTTGTCTGGGACGATCTGCGGAGCCTGTGCCTCTTCAGCTACCACCGATTGAGAGACTGCATATTGGGACTGAAACTTCTGGGACAGAGGGGATGGGAAGCCCTTAAGTATCTAGGAAGTCTTGTGCAGTATTGGGGTCTGGAACTAAAAAAGAGTGCCATTAGTCTGCTTGATACCATAGCAATAGTAGTAGCTGAGGGAACAGATAGAATTATAGAATTCATACTAAGAATTTGTAGAGCTATCCACCACATACCTAGAAGAGTAAGACAGGGCTTTGAAGCAGCTTTGCTATAAAATGGGGAACAAGTGGTCAAAAAGCTGGCCTGCTGTAAGGGAAAGATTAAGAAGAACTGTGCCAGCAGCAGAGAGAGTAAGTGCAGCAGAGGGAGTAGGAGCAGCATCTCAAGACTTAGCTAAGCATGGAGCACTTACAACCAGCAACACAGCCCACAATAATGAGGCTTGTGCCTGGCTGCAAGCACAAGAGGAGAATGAAGAAGAAGTA";
    let ref_aa = translate(reference, false, false, &codon_table)?;
    let cons_aa =  translate(consensus,false, false, &codon_table)?;

    // let score = |a: u8, b: u8| if a == b { 1i32 } else { -1i32 };

    let mut aligner = Aligner::with_capacity(cons_aa.len(), ref_aa.len(), -5, -1, bio::scores::blosum62);
    let alignment = aligner.local(cons_aa.as_slice(), ref_aa.as_slice());


    // let codon_table: HashMap<&[u8; 3], &[u8; 1]> = HashMap::from([
    //     (b"TTT", "F".as_bytes()), ("TTC".as_bytes(), "F".as_bytes()), ("TTA".as_bytes(), "L".as_bytes()), ("TTG".as_bytes(), "L".as_bytes()), ("CTT".as_bytes(), "L".as_bytes()), ("CTC".as_bytes(), "L".as_bytes()), ("CTA".as_bytes(), "L".as_bytes()), ("CTG".as_bytes(), "L".as_bytes()),
    //     ("ATT".as_bytes(), "I".as_bytes()), ("ATC".as_bytes(), "I".as_bytes()), ("ATA".as_bytes(), "I".as_bytes()), ("ATG".as_bytes(), "M".as_bytes()), ("GTT".as_bytes(), "V".as_bytes()), ("GTC".as_bytes(), "V".as_bytes()), ("GTA".as_bytes(), "V".as_bytes()), ("GTG".as_bytes(), "V".as_bytes()),
    //     ("TCT".as_bytes(), "S".as_bytes()), ("TCC".as_bytes(), "S".as_bytes()), ("TCA".as_bytes(), "S".as_bytes()), ("TCG".as_bytes(), "S".as_bytes()), ("CCT".as_bytes(), "P".as_bytes()), ("CCC".as_bytes(), "P".as_bytes()), ("CCA".as_bytes(), "P".as_bytes()), ("CCG".as_bytes(), "P".as_bytes()),
    //     ("ACT".as_bytes(), "T".as_bytes()), ("ACC".as_bytes(), "T".as_bytes()), ("ACA".as_bytes(), "T".as_bytes()), ("ACG".as_bytes(), "T".as_bytes()), ("GCT".as_bytes(), "A".as_bytes()), ("GCC".as_bytes(), "A".as_bytes()), ("GCA".as_bytes(), "A".as_bytes()), ("GCG".as_bytes(), "A".as_bytes()),
    //     ("TAT".as_bytes(), "Y".as_bytes()), ("TAC".as_bytes(), "Y".as_bytes()), ("CAT".as_bytes(), "H".as_bytes()), ("CAC".as_bytes(), "H".as_bytes()), ("CAA".as_bytes(), "Q".as_bytes()), ("CAG".as_bytes(), "Q".as_bytes()),
    //     ("AAT".as_bytes(), "N".as_bytes()), ("AAC".as_bytes(), "N".as_bytes()), ("AAA".as_bytes(), "K".as_bytes()), ("AAG".as_bytes(), "K".as_bytes()), ("GAT".as_bytes(), "D".as_bytes()), ("GAC".as_bytes(), "D".as_bytes()), ("GAA".as_bytes(), "E".as_bytes()), ("GAG".as_bytes(), "E".as_bytes()),
    //     ("TGT".as_bytes(), "C".as_bytes()), ("TGC".as_bytes(), "C".as_bytes()), ("TGG".as_bytes(), "W".as_bytes()), ("CGT".as_bytes(), "R".as_bytes()), ("CGC".as_bytes(), "R".as_bytes()), ("CGA".as_bytes(), "R".as_bytes()), ("CGG".as_bytes(), "R".as_bytes()),
    //     ("AGT".as_bytes(), "S".as_bytes()), ("AGC".as_bytes(), "S".as_bytes()), ("AGA".as_bytes(), "R".as_bytes()), ("AGG".as_bytes(), "R".as_bytes()), ("GGT".as_bytes(), "G".as_bytes()), ("GGC".as_bytes(), "G".as_bytes()), ("GGA".as_bytes(), "G".as_bytes()), ("GGG".as_bytes(), "G".as_bytes())]);


    println!("{}", alignment.pretty(cons_aa.as_slice(), ref_aa.as_slice(), 160));

    Ok(())
}